/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

import br.com.login.Controller.LoginController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Felipe
 */
public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroView
     */
    public CadastroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuarioCadastro = new javax.swing.JTextField();
        txt_confirmarSenha = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        txt_emailCadastro = new javax.swing.JTextField();
        txt_senhaCadastro = new javax.swing.JPasswordField();
        txt_cpfCadastro = new javax.swing.JTextField();
        btn_loginCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usuarioCadastro.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        txt_usuarioCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_usuarioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usuarioCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 140, 211, 31));

        txt_confirmarSenha.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        txt_confirmarSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txt_confirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 320, 211, 32));

        btn_login.setContentAreaFilled(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 100, 30));

        txt_emailCadastro.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txt_emailCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_emailCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_emailCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 75, 211, 32));

        txt_senhaCadastro.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        txt_senhaCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txt_senhaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 256, 211, 32));

        txt_cpfCadastro.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        txt_cpfCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cpfCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpfCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cpfCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 211, 31));

        btn_loginCadastro.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_loginCadastro.setForeground(new java.awt.Color(122, 153, 186));
        btn_loginCadastro.setText("login");
        btn_loginCadastro.setBorder(null);
        btn_loginCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_loginCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_loginCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastro (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioCadastroActionPerformed

    private void txt_emailCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailCadastroActionPerformed

    private void txt_cpfCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpfCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpfCadastroActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
    
        if (txt_usuarioCadastro.getText().matches("")||txt_emailCadastro.getText().matches("")||txt_senhaCadastro.getText().matches("")||txt_cpfCadastro.getText().matches("")||txt_confirmarSenha.getText().matches("")){
        JOptionPane.showMessageDialog(rootPane, "Preencha dodos os campos");
        }
        else {
        LoginController cadastro = new LoginController();
        try {
            cadastro.cadastroUsuario(this);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroView.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        LoginView login = new LoginView();
        login.setVisible(true);
        }
            
    
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_loginCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginCadastroActionPerformed

        LoginView log = new LoginView();
        log.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btn_loginCadastroActionPerformed

    
    public JTextField getTxt_emailCadastro() {
        return txt_emailCadastro;
    }

    public void setTxt_emailCadastro(JTextField txt_emailCadastro) {
        this.txt_emailCadastro = txt_emailCadastro;
    }

    public JPasswordField getTxt_senhaCadastro() {
        return txt_confirmarSenha;
    }

    public void setTxt_senhaCadastro(JPasswordField txt_senhaCadastro) {
        this.txt_confirmarSenha = txt_senhaCadastro;
    }

    public JTextField getTxt_usuarioCadastro() {
        return txt_usuarioCadastro;
    }

    public void setTxt_usuarioCadastro(JTextField txt_usuarioCadastro) {
        this.txt_usuarioCadastro = txt_usuarioCadastro;
    }

    public JTextField getTxt_cpfCadastro() {
        return txt_cpfCadastro;
    }

    public void setTxt_cpfCadastro(JTextField txt_cpfCadastro) {
        this.txt_cpfCadastro = txt_cpfCadastro;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_loginCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txt_confirmarSenha;
    private javax.swing.JTextField txt_cpfCadastro;
    private javax.swing.JTextField txt_emailCadastro;
    private javax.swing.JPasswordField txt_senhaCadastro;
    private javax.swing.JTextField txt_usuarioCadastro;
    // End of variables declaration//GEN-END:variables

    private LoginView LoginView() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
