/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

import br.com.login.Controller.LoginController;
import br.com.login.DAO.LoginDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import br.com.menu.view.menu;
import java.awt.Menu;
import javax.security.auth.login.LoginException;
/**
 *
 * @author Felipe
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_emailLogin = new javax.swing.JTextField();
        txt_senhaLogin = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_cadastro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_emailLogin.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txt_emailLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_emailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txt_emailLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 230, 34));

        txt_senhaLogin.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txt_senhaLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txt_senhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 230, 34));

        btn_login.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(122, 153, 186));
        btn_login.setText("login");
        btn_login.setBorder(null);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 303, 80, 30));

        btn_cadastro.setContentAreaFilled(false);
        btn_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 70, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailLoginActionPerformed

    private void btn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroActionPerformed

        CadastroView cadastro = new CadastroView();
        this.setVisible(false);
        cadastro.setVisible(true);
    }//GEN-LAST:event_btn_cadastroActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
    String email = txt_emailLogin.getText();
    char[] senhaChars = txt_senhaLogin.getPassword();
    String senha = new String(senhaChars);

    if (email.isEmpty() || senhaChars.length == 0) {
        JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
    } else {
        LoginDAO loginDAO = new LoginDAO();
        try {
            boolean loginValido = loginDAO.login(email, senha);

            if (loginValido) {
                // Login bem-sucedido
                menu m = new menu();
                m.setVisible(true);
                this.dispose(); // Fechar a janela de login atual
            } else {
                // Dados incorretos ou usuário não encontrado
                JOptionPane.showMessageDialog(rootPane, "Dados incorretos ou usuário não encontrado");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_btn_loginActionPerformed

    public JTextField getTxt_emailLogin() {
        return txt_emailLogin;
    }

    public void setTxt_emailLogin(JTextField txt_emailLogin) {
        this.txt_emailLogin = txt_emailLogin;
    }

    public JPasswordField getTxt_senhaLogin() {
        return txt_senhaLogin;
    }

    public void setTxt_senhaLogin(JPasswordField txt_senhaLogin) {
        this.txt_senhaLogin = txt_senhaLogin;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastro;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_emailLogin;
    private javax.swing.JPasswordField txt_senhaLogin;
    // End of variables declaration//GEN-END:variables
}
