/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.menu.view;

import br.com.tmb.view.TmbView;
import br.com.imc.view.imc;
import br.com.alimentos.view.DicaNutricionalDAO;
import br.com.alimentos.view.alimentos;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_alimentosMenu = new javax.swing.JButton();
        btn_tmbMenu = new javax.swing.JButton();
        btn_imcMenu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_alimentosMenu.setContentAreaFilled(false);
        btn_alimentosMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_alimentosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alimentosMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alimentosMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 230, 100));

        btn_tmbMenu.setContentAreaFilled(false);
        btn_tmbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tmbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tmbMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tmbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 200, 230, 100));

        btn_imcMenu.setContentAreaFilled(false);
        btn_imcMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_imcMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imcMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_imcMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 230, 100));

        jButton1.setText("Dicas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tmbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tmbMenuActionPerformed

        TmbView tmb = new TmbView();
        tmb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_tmbMenuActionPerformed

    private void btn_imcMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imcMenuActionPerformed

        imc IMC = new imc();
        IMC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_imcMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DicaNutricionalDAO dica = new DicaNutricionalDAO();
        String dicaNutricional = dica.obterDicaAleatoria();

        JOptionPane.showMessageDialog(this, dicaNutricional, "Dica Nutricional", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_alimentosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alimentosMenuActionPerformed
    alimentos comida = new alimentos(); 
    comida.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btn_alimentosMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alimentosMenu;
    private javax.swing.JButton btn_imcMenu;
    private javax.swing.JButton btn_tmbMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
