/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.tmb.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import br.com.login.DAO.Conexao;
import br.com.menu.view.menu;
import java.sql.Time;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;

public class TmbView extends javax.swing.JFrame {

   private ButtonGroup grupoSexo;
    private ButtonGroup grupoAtividade;
    private DecimalFormat decimalFormat;
    private Connection connection;


    private final Conexao conexao;

    public TmbView() {
        initComponents();
        conexao = new Conexao();
    
        

        // Inicialização dos grupos de radio buttons
        grupoSexo = new ButtonGroup();
        grupoSexo.add(rb_masculino);
        grupoSexo.add(rb_feminino);

        grupoAtividade = new ButtonGroup();
        grupoAtividade.add(rb_leve);
        grupoAtividade.add(rb_moderado);
        grupoAtividade.add(rb_pesado);
        grupoAtividade.add(rb_sedentario);

        decimalFormat = new DecimalFormat("#.##");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_pesoTmb = new javax.swing.JTextField();
        txt_alturaTmb = new javax.swing.JTextField();
        txt_idadeTmb = new javax.swing.JTextField();
        rb_masculino = new javax.swing.JRadioButton();
        rb_feminino = new javax.swing.JRadioButton();
        btn_calcularTmb = new javax.swing.JButton();
        txt_resultadoTmb = new javax.swing.JTextField();
        rb_leve = new javax.swing.JRadioButton();
        rb_pesado = new javax.swing.JRadioButton();
        rb_moderado = new javax.swing.JRadioButton();
        rb_sedentario = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_gravarTMB = new javax.swing.JButton();
        label_tela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pesoTmb.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txt_pesoTmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_pesoTmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesoTmbActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pesoTmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 151, 220, 40));

        txt_alturaTmb.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txt_alturaTmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_alturaTmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alturaTmbActionPerformed(evt);
            }
        });
        getContentPane().add(txt_alturaTmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 239, 220, 40));

        txt_idadeTmb.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txt_idadeTmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_idadeTmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idadeTmbActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idadeTmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 319, 220, 40));

        rb_masculino.setText("masculino");
        rb_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_masculinoActionPerformed(evt);
            }
        });
        getContentPane().add(rb_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        rb_feminino.setText("feminino");
        getContentPane().add(rb_feminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        btn_calcularTmb.setContentAreaFilled(false);
        btn_calcularTmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_calcularTmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularTmbActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calcularTmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 406, 128, 30));

        txt_resultadoTmb.setEditable(false);
        txt_resultadoTmb.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        txt_resultadoTmb.setBorder(null);
        txt_resultadoTmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resultadoTmbActionPerformed(evt);
            }
        });
        getContentPane().add(txt_resultadoTmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 240, 30));

        rb_leve.setText("Atividade leve");
        getContentPane().add(rb_leve, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        rb_pesado.setText("Muito ativo");
        rb_pesado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_pesadoActionPerformed(evt);
            }
        });
        getContentPane().add(rb_pesado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        rb_moderado.setText("Moderadamente ativo");
        getContentPane().add(rb_moderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        rb_sedentario.setText("Sedentario");
        getContentPane().add(rb_sedentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        jLabel1.setText("Selecione seu nivel de atividade:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        jButton1.setText("Voltar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        jLabel5.setText("Selecione seu sexo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        btn_gravarTMB.setText("Gravar TMB");
        btn_gravarTMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravarTMBActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gravarTMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        label_tela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tmb.png"))); // NOI18N
        label_tela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(label_tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pesoTmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesoTmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesoTmbActionPerformed

    private void txt_alturaTmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alturaTmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alturaTmbActionPerformed

    private void txt_idadeTmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idadeTmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idadeTmbActionPerformed

    private void rb_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_masculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_masculinoActionPerformed

    private void btn_calcularTmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularTmbActionPerformed
        // Obter os valores dos campos de entrada
        double peso = Double.parseDouble(txt_pesoTmb.getText());
        double altura = Double.parseDouble(txt_alturaTmb.getText());
        int idade = Integer.parseInt(txt_idadeTmb.getText());
        
        // Calcular a TMB de acordo com o sexo
        double tmb;
        if (rb_masculino.isSelected()) {
            tmb = 66.5 + (13.75 * peso) + (5 * altura) - (6.75 * idade);
        } else {
            tmb = 655.1 + (9.563 * peso) + (1.85 * altura) - (4.676 * idade);
        }
        
        // Aplicar o fator de atividade
        double fatorAtividade = 1.0;
        if (rb_sedentario.isSelected()) {
            fatorAtividade = 1.2;
        } else if (rb_leve.isSelected()) {
            fatorAtividade = 1.375;
        } else if (rb_moderado.isSelected()) {
            fatorAtividade = 1.55;
        } else if (rb_pesado.isSelected()) {
            fatorAtividade = 1.725;
        }
        
        // Calcular a TMB com o fator de atividade
        double tmbComAtividade = tmb * fatorAtividade;
        
        // Formatar o resultado com dois números após a vírgula
        String resultadoFormatado = decimalFormat.format(tmbComAtividade);
        
        // Exibir o resultado
        txt_resultadoTmb.setText("Seu TMB é de " + resultadoFormatado + " Kcal");
    }//GEN-LAST:event_btn_calcularTmbActionPerformed

    private void rb_pesadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_pesadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_pesadoActionPerformed

    private void txt_resultadoTmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resultadoTmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resultadoTmbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        menu Menu = new menu();
        Menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_gravarTMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravarTMBActionPerformed
     
        if (txt_pesoTmb.getText().isEmpty() || txt_alturaTmb.getText().isEmpty()) {
        int escolha = JOptionPane.showOptionDialog(this, "Nenhum dado inserido. Deseja ver os últimos 5 TMBs?", "Erro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sim", "Não"}, null);

        if (escolha == JOptionPane.YES_OPTION) {
            verUltimos5TMBs();
        }
        return;
    }
        if (txt_pesoTmb.getText().isEmpty() || txt_alturaTmb.getText().isEmpty()) {
        int escolha = JOptionPane.showOptionDialog(this, "Nenhum dado inserido. Deseja ver os últimos 5 TMBs?", "Erro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sim", "Não"}, null);

        if (escolha == JOptionPane.YES_OPTION) {
            verUltimos5TMBs();
        }
        return;
    }

    double peso = Double.parseDouble(txt_pesoTmb.getText());
    double altura = Double.parseDouble(txt_alturaTmb.getText());
    int idade = Integer.parseInt(txt_idadeTmb.getText());

    // Calcular a TMB de acordo com o sexo
    double tmb;
    if (rb_masculino.isSelected()) {
        tmb = 66.5 + (13.75 * peso) + (5 * altura) - (6.75 * idade);
    } else {
        tmb = 655.1 + (9.563 * peso) + (1.85 * altura) - (4.676 * idade);
    }

    // Aplicar o fator de atividade
    double fatorAtividade = 1.0;
    if (rb_sedentario.isSelected()) {
        fatorAtividade = 1.2;
    } else if (rb_leve.isSelected()) {
        fatorAtividade = 1.375;
    } else if (rb_moderado.isSelected()) {
        fatorAtividade = 1.55;
    } else if (rb_pesado.isSelected()) {
        fatorAtividade = 1.725;
    }

    // Calcular a TMB com o fator de atividade
    double tmbComAtividade = tmb * fatorAtividade;

    gravarTMB(tmbComAtividade);

    }//GEN-LAST:event_btn_gravarTMBActionPerformed

    private void gravarTMB(double tmb) {
    try (Connection connection = conexao.getConnection()) {
        String query = "INSERT INTO tmb_data (tmb, data, horario) VALUES (?, CURDATE(), CURTIME())";
        PreparedStatement statement = connection.prepareStatement(query);
        statement.setDouble(1, tmb);
        statement.executeUpdate();
        JOptionPane.showMessageDialog(this, "TMB gravado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        // Limpar os campos de texto
        txt_pesoTmb.setText("");
        txt_alturaTmb.setText("");
        txt_idadeTmb.setText("");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao gravar TMB: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}


private void verUltimos5TMBs() {
    try (Connection connection = conexao.getConnection()) {
        String query = "SELECT * FROM tmb_data ORDER BY id DESC LIMIT 5";
        PreparedStatement statement = connection.prepareStatement(query);
        ResultSet resultSet = statement.executeQuery();
        StringBuilder sb = new StringBuilder();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        while (resultSet.next()) {
            double tmb = resultSet.getDouble("tmb");
            Date data = resultSet.getDate("data");
            Time horario = resultSet.getTime("horario");
            String dataFormatada = dateFormat.format(data);
            sb.append("TMB: ").append(tmb).append(", Data: ").append(dataFormatada).append(", Horário: ").append(horario).append("\n");
        }
        JOptionPane.showMessageDialog(this, sb.toString(), "Últimos 5 TMBs", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao buscar os últimos 5 TMBs: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TmbView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TmbView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TmbView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TmbView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TmbView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcularTmb;
    private javax.swing.JButton btn_gravarTMB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label_tela;
    private javax.swing.JRadioButton rb_feminino;
    private javax.swing.JRadioButton rb_leve;
    private javax.swing.JRadioButton rb_masculino;
    private javax.swing.JRadioButton rb_moderado;
    private javax.swing.JRadioButton rb_pesado;
    private javax.swing.JRadioButton rb_sedentario;
    private javax.swing.JTextField txt_alturaTmb;
    private javax.swing.JTextField txt_idadeTmb;
    private javax.swing.JTextField txt_pesoTmb;
    private javax.swing.JTextField txt_resultadoTmb;
    // End of variables declaration//GEN-END:variables
}
